version: '3.8'

services:
  xiansai-server:
    image: ${DOCKER_IMAGE:-xiansai/server:latest}
    container_name: xiansai-server
    environment:
      # Core Settings
      - ASPNETCORE_ENVIRONMENT=Production
      - SERVICE_TYPE=${SERVICE_TYPE:---all}
      
      # Database
      - MongoDB__ConnectionString=${MongoDB__ConnectionString}
      - MongoDB__DatabaseName=${MongoDB__DatabaseName:-xiansai_prod}
      
      # Temporal Workflow Engine
      - Temporal__CertificateBase64=${Temporal__CertificateBase64}
      - Temporal__PrivateKeyBase64=${Temporal__PrivateKeyBase64}
      - Temporal__FlowServerUrl=${Temporal__FlowServerUrl}
      - Temporal__FlowServerNamespace=${Temporal__FlowServerNamespace}
      
      # Certificates
      - Certificates__AppServerPfxBase64=${Certificates__AppServerPfxBase64}
      - Certificates__AppServerCertPassword=${Certificates__AppServerCertPassword}
      
      # Cache
      - Cache__Provider=${Cache__Provider:-redis}
      - Cache__Redis__ConnectionString=${Cache__Redis__ConnectionString}
      
      # LLM/AI
      - Llm__Provider=${Llm__Provider:-openai}
      - Llm__Model=${Llm__Model:-gpt-4o-mini}
      - Llm__ApiKey=${Llm__ApiKey}
      
      # Email
      - Email__Provider=${Email__Provider:-azure}
      - Email__Azure__ConnectionString=${Email__Azure__ConnectionString}
      - Email__Azure__SenderEmail=${Email__Azure__SenderEmail}
      
      # Auth0 Authentication
      - Auth0__Domain=${Auth0__Domain}
      - Auth0__Audience=${Auth0__Audience}
      - Auth0__ClientId=${Auth0__ClientId}
      - Auth0__ClientSecret=${Auth0__ClientSecret}
      - Auth0__ManagementApi__ClientId=${Auth0__ManagementApi__ClientId}
      - Auth0__ManagementApi__ClientSecret=${Auth0__ManagementApi__ClientSecret}
      
      # Azure B2C Authentication (Alternative)
      - AzureB2C__TenantId=${AzureB2C__TenantId}
      - AzureB2C__Domain=${AzureB2C__Domain}
      - AzureB2C__ClientId=${AzureB2C__ClientId}
      - AzureB2C__ClientSecret=${AzureB2C__ClientSecret}
      - AzureB2C__Audience=${AzureB2C__Audience}
      
      # CORS (Arrays using index notation)
      - Cors__AllowedOrigins__0=${Cors__AllowedOrigins__0:-https://xians.ai}
      - Cors__AllowedOrigins__1=${Cors__AllowedOrigins__1:-https://www.xians.ai}
      - Cors__AllowedOrigins__2=${Cors__AllowedOrigins__2}
      - Cors__AllowedOrigins__3=${Cors__AllowedOrigins__3}
      
      # WebSockets
      - WebSockets__Enabled=${WebSockets__Enabled:-true}
      - WebSockets__Secrets__${WebSockets__ClientName:-default}=${WebSockets__Secret}
      - WebSockets__UserId=websocket
      
    ports:
      - "${HTTP_PORT:-5000}:80"
      - "${HTTPS_PORT:-5001}:443"
    volumes:
      # Optional: Mount certificates from files instead of base64
      - ./certs:/app/certs:ro
    networks:
      - xiansai-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

networks:
  xiansai-network:
    driver: bridge
    name: xiansai-network 