
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: xians-keycloak-dev${ENVIRONMENT_SUFFIX:-}
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin123
      - KC_DB=dev-mem
    networks:
      - xians-community-edition
    volumes:
      - ./keycloak-realm:/opt/keycloak/data/import
    command: ["start-dev", "--import-realm"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  xiansai-server-dev:
    image: ${SERVER_IMAGE:-99xio/xiansai-server:latest}
    container_name: xians-server-dev${ENVIRONMENT_SUFFIX:-}
    restart: unless-stopped
    ports:
      - "5005:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENV:-Development}
    env_file:
      - .env
    networks:
      - xians-community-edition
    volumes:
      - xiansai-data:/app/data
    depends_on:
      keycloak:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: ${SERVER_MEMORY_LIMIT:-1G}
        reservations:
          memory: ${SERVER_MEMORY_RESERVATION:-512M}
    logging:
      driver: ${LOGGING_DRIVER:-local}
      options:
        max-size: ${LOG_MAX_SIZE:-50m}
        max-file: ${LOG_MAX_FILE:-2}


networks:
  xians-community-edition:
    driver: bridge

volumes:
  xiansai-data: